In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from deepgd.datasets import SuiteSparseDataset, RomeDataset
from deepgd.data import ScalableGraphDataUniformSample, ScalableGraphDataExponentialSample, DenseGraphData

In [3]:
device = 'cpu'

In [4]:
dataset = SuiteSparseDataset(
    min_nodes=0,
    max_nodes=7500,
    limit=10000,
    datatype=ScalableGraphDataUniformSample,
    datatype_args=dict(
        device=device,
        landmarks=10,
        random_edges=10
    )
)

In [5]:
dataset = SuiteSparseDataset(
    min_nodes=0,
    max_nodes=7500,
    limit=10000,
    datatype=ScalableGraphDataUniformSample,
    datatype_args=dict(
        device=device,
        landmarks=20,
        random_edges=20
    )
)

Processing...


Load graphs:   0%|          | 0/1082 [00:00<?, ?it/s]

/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1704987091277/work/aten/src/ATen/native/TensorShape.cpp:3550.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


Saving 1138_bus
Saving 494_bus
Saving 662_bus
Saving 685_bus
Saving arc130
Saving ash292
Saving ash85
Saving bcspwr01
Saving bcspwr02
Saving bcspwr03
Saving bcspwr04
Saving bcspwr05
Saving bcspwr06
Saving bcspwr07
Saving bcspwr08
Saving bcspwr09
Saving bcspwr10
Saving bcsstk01
Saving bcsstk02
Saving bcsstk04
Saving bcsstk05
Saving bcsstk06
Saving bcsstk07
Saving bcsstk09
Saving bcsstk13
Saving bcsstk19
Saving bcsstk23
Saving bcsstk24
Saving bcsstk26
Saving bcsstk27
Saving bcsstk28
Saving bcsstm07
Saving bcsstm27
Saving bp_0
Saving bp_1000
Saving bp_1200
Saving bp_1400
Saving bp_1600
Saving bp_200
Saving bp_400
Saving bp_600
Saving bp_800
Saving can_1054
Saving can_1072
Saving can_144
Saving can_161
Saving can_187
Saving can_229
Saving can_24
Saving can_256
Saving can_268
Saving can_292
Saving can_445
Saving can_61
Saving can_62
Saving can_634
Saving can_715
Saving can_73
Saving can_838
Saving can_96
Saving curtis54
Saving dwt_1005
Saving dwt_1007
Saving dwt_1242
Saving dwt_162
Saving d

Done!


In [6]:
dataset = SuiteSparseDataset(
    min_nodes=0,
    max_nodes=7500,
    limit=10000,
    datatype=ScalableGraphDataUniformSample,
    datatype_args=dict(
        device=device,
        landmarks=50,
        random_edges=50
    )
)

Processing...


Load graphs:   0%|          | 0/1082 [00:00<?, ?it/s]

Saving 1138_bus
Saving 494_bus
Saving 662_bus
Saving 685_bus
Saving arc130
Saving ash292
Saving ash85
Saving bcspwr01
Saving bcspwr02
Saving bcspwr03
Saving bcspwr04
Saving bcspwr05
Saving bcspwr06
Saving bcspwr07
Saving bcspwr08
Saving bcspwr09
Saving bcspwr10
Saving bcsstk01
Saving bcsstk02
Saving bcsstk04
Saving bcsstk05
Saving bcsstk06
Saving bcsstk07
Saving bcsstk09
Saving bcsstk13
Saving bcsstk19
Saving bcsstk23
Saving bcsstk24
Saving bcsstk26
Saving bcsstk27
Saving bcsstk28
Saving bcsstm07
Saving bcsstm27
Saving bp_0
Saving bp_1000
Saving bp_1200
Saving bp_1400
Saving bp_1600
Saving bp_200
Saving bp_400
Saving bp_600
Saving bp_800
Saving can_1054
Saving can_1072
Saving can_144
Saving can_161
Saving can_187
Saving can_229
Saving can_24
Saving can_256
Saving can_268
Saving can_292
Saving can_445
Saving can_61
Saving can_62
Saving can_634
Saving can_715
Saving can_73
Saving can_838
Saving can_96
Saving curtis54
Saving dwt_1005
Saving dwt_1007
Saving dwt_1242
Saving dwt_162
Saving d

Done!


In [6]:
dataset[0]

ScalableGraphData(x=[1138, 2], G=DiGraph named '1138_bus' with 1138 nodes and 2916 edges, n=1138, m=2916, raw_edge_index=[2, 2916], raw_edge_attr=[2916, 2], edge_index=[2, 124410], edge_attr=[124410, 2], edge_weight=[124410], full_edge_index=[2, 124410], full_edge_attr=[124410, 2])

In [7]:
dataset = RomeDataset(
    datatype=ScalableGraphDataUniformSample,
    datatype_args=dict(
        device=device,
        landmarks=10,
        random_edges=10
    )
)

Extracting datasets/RomeDataset/raw/rome-graphml.tgz
Processing...


Loading graphs:   0%|          | 0/11534 [00:00<?, ?it/s]

/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1702400234613/work/aten/src/ATen/native/TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Done!


In [4]:
dataset = RomeDataset(
    datatype=ScalableGraphDataExponentialSample,
    datatype_args=dict(
        device=device,
        landmarks=10,
        sampling_factor=0.2
    )
)

Processing...


Loading graphs:   0%|          | 0/11534 [00:00<?, ?it/s]

/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1702400234613/work/aten/src/ATen/native/TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Done!


In [8]:
dataset = RomeDataset(
    datatype=DenseGraphData,
    datatype_args=dict(
        device=device
    )
)

Processing...


Loading graphs:   0%|          | 0/11534 [00:00<?, ?it/s]

Done!


In [5]:
dataset[0]

Data(x=[28, 2], G=DiGraph named 'grafo113.28' with 28 nodes and 62 edges, n=[1], m=[1], raw_edge_index=[2, 62], raw_edge_attr=[62, 2], edge_index=[2, 695], edge_attr=[695, 2], edge_weight=[695], full_edge_index=[2, 695], full_edge_attr=[695, 2])

In [10]:
import torch
torch.bernoulli(torch.tensor([0.5, 0.5]))

tensor([0., 1.])

In [15]:
torch.nonzero(torch.bernoulli(torch.tensor([0.5, 0.5])))

tensor([[0],
        [1]])

In [20]:
torch.stack(torch.meshgrid(torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6]))).view(2, -1)

tensor([[1, 1, 1, 2, 2, 2, 3, 3, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6]])